<?php

/**
 * @file
 * The embetty module.
 */

/**
 * Implements hook_menu().
 */
function embetty_menu() {
  $items['admin/config/services/embetty'] = array(
    'title' => 'Embetty server',
    'description' => 'Configure the embetty server settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('embetty_configuration_form'),
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

/**
 * Implements hook_page_build().
 */
function embetty_page_build(&$page) {
  $server = variable_get('embetty_server', '');
  $embetty = [
    '#tag' => 'meta',
    '#attributes' => [
      'data-embetty-server' => $server,
    ],
  ];
  if (!empty($server)) {
    drupal_add_html_head($embetty, 'embetty-server');
    drupal_add_js('/sites/all/libraries/embetty/embetty.js');
  }
}

/**
 * Configuration form.
 */
function embetty_configuration_form($form, &$form_state) {
  $form = [];
  $form['server'] = [
    '#type' => 'textfield',
    '#title' => t('Server'),
    '#default_value' => variable_get('embetty_server', ''),
  ];
  $form['actions'] = [
    '#type' => 'actions',
  ];
  $form['actions']['submit'] = [
    '#type' => 'submit',
    '#value' => t('Submit'),
  ];
  return $form;
}

/**
 * Configuration form submit handler.
 */
function embetty_configuration_form_submit($form, &$form_state) {
  variable_set('embetty_server', $form_state['values']['server']);
}
