<?php

/**
 * @file
 * Embetty module.
 */

/**
 * Implements hook_page_attachments().
 */
function embetty_page_attachments(array &$attachments) {
  $embetty = [
    '#tag' => 'meta',
    '#attributes' => [
      'data-embetty-server' => $config = \Drupal::config('embetty.settings')->get('server'),
    ],
  ];
  $attachments['#attached']['html_head'][] = [$embetty, 'embetty-server'];
  $attachments['#attached']['library'][] = 'embetty/embetty';
}
